spring:
  ai:
    alibaba:
      access-key-id: ${ALIBABA_ACCESS_KEY}
      access-key-secret: ${ALIBABA_SECRET_KEY}
      region: cn-hangzhou
      dashscope: XXX
      chat:
        model: qwen-max
        endpoint: https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation 