server:
  port: 8080

spring:
  application:
    name: chy-agents
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key}
      chat-model: gpt-4
      embedding-model: text-embedding-3-small
    alibaba:
      dashscope:
        api-key: ${ALIBABA_API_KEY:your-alibaba-api-key}
        model: qwen-max

logging:
  level:
    root: INFO
    com.chy.agents: DEBUG
    org.springframework.ai: INFO 